updated the updaters (again)

diff --git a/wpsd-update b/wpsd-update
--- a/wpsd-update
+++ b/wpsd-update
@@ -151,6 +151,33 @@ perform_update() {
     pkill .wpsd-slipstream-tasks > /dev/null 2>&1
     pkill .wpsd-running-tasks > /dev/null 2>&1
 
+    systemctl is-active --quiet cron.service && systemctl stop cron.service > /dev/null 2>&1
+    systemctl is-active --quiet wpsd-running-tasks.timer && systemctl stop wpsd-running-tasks.timer > /dev/null 2>&1
+    systemctl is-active --quiet wpsd-running-tasks.service && systemctl stop wpsd-running-tasks.service > /dev/null 2>&1
+    systemctl is-active --quiet wpsd-nightly-tasks.timer && systemctl stop wpsd-nightly-tasks.timer > /dev/null 2>&1
+    systemctl is-active --quiet wpsd-nightly-tasks.service && systemctl stop wpsd-nightly-tasks.service > /dev/null 2>&1
+    systemctl is-active --quiet wpsd-cache.timer && systemctl stop wpsd-cache.timer > /dev/null 2>&1
+
+    if [ -t 1 ] ; then
+        if ! [ $(cat /lib/systemd/system/nginx.service | grep -o "mkdir") ]; then
+            sed -i '\/PIDFile=\/run\/nginx.pid/a ExecStartPre=\/bin\/mkdir -p \/var\/log\/nginx' /lib/systemd/system/nginx.service
+            systemctl daemon-reload
+            systemctl restart nginx.service
+            echo -e "  ${NOTE} ${COL_LIGHT_YELLOW}Note:${COL_NC} Web server configuration has been updated; restarting update..."
+            exec "$0" "$@"
+            exit 1
+        fi
+    fi
+
+    echo -e "\n${BULL} Checking connectivity to the WPSD Update System..."
+    conn_check
+    if $connection_established; then
+        echo -e "  ${COL_BRIGHT_GREEN}${TICK} Connection established! Starting update proces...\n"
+    else
+        echo -e "  ${CROSS} ${COL_BRIGHT_RED}ERROR:${COL_NC} Cannot connect to the WPSD Update System. Try again later. Exiting...\n"
+        exit 1
+    fi
+
     if [ "$DISPLAY_VALUE" == "Nextion" ] ; then
         if [ "${OS_VER}" -ge 12 ] ; then
             systemctl stop nextiondriver.service > /dev/null 2>&1
@@ -173,33 +200,6 @@ perform_update() {
             systemctl stop mmdvmhost.service > /dev/null 2>&1
             /usr/local/sbin/.wpsd-oled.text.py --text1 "Updating..." --text2 "Please Wait..." > /dev/null 2>&1
         fi
-    fi
-
-    systemctl is-active --quiet cron.service && systemctl stop cron.service > /dev/null 2>&1
-    systemctl is-active --quiet wpsd-running-tasks.timer && systemctl stop wpsd-running-tasks.timer > /dev/null 2>&1
-    systemctl is-active --quiet wpsd-running-tasks.service && systemctl stop wpsd-running-tasks.service > /dev/null 2>&1
-    systemctl is-active --quiet wpsd-nightly-tasks.timer && systemctl stop wpsd-nightly-tasks.timer > /dev/null 2>&1
-    systemctl is-active --quiet wpsd-nightly-tasks.service && systemctl stop wpsd-nightly-tasks.service > /dev/null 2>&1
-    systemctl is-active --quiet wpsd-cache.timer && systemctl stop wpsd-cache.timer > /dev/null 2>&1
-
-    if [ -t 1 ] ; then
-        if ! [ $(cat /lib/systemd/system/nginx.service | grep -o "mkdir") ]; then
-            sed -i '\/PIDFile=\/run\/nginx.pid/a ExecStartPre=\/bin\/mkdir -p \/var\/log\/nginx' /lib/systemd/system/nginx.service
-            systemctl daemon-reload
-            systemctl restart nginx.service
-            echo -e "  ${NOTE} ${COL_LIGHT_YELLOW}Note:${COL_NC} Web server configuration has been updated; restarting update..."
-            exec "$0" "$@"
-            exit 1
-        fi
-    fi
-
-    echo -e "\n${BULL} Checking connectivity to the WPSD Update System..."
-    conn_check
-    if $connection_established; then
-        echo -e "  ${COL_BRIGHT_GREEN}${TICK} Connection established!\n"
-    else
-        echo -e "  ${CROSS} ${COL_BRIGHT_RED}ERROR:${COL_NC} Cannot connect to the WPSD Update System. Try again later. Exiting...\n"
-        exit 1
     fi
 
     echo -e "${BULL} Updating WPSD Utilities and Support Programs..."
